# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-07 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='uuid',
            field=models.CharField(db_index=True, help_text='UUID', max_length=50, unique=True, verbose_name='UUID'),
        ),
    ]
