# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-04 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='机房名称')),
                ('address', models.CharField(max_length=200, verbose_name='机房地址')),
                ('phone', models.CharField(max_length=15, verbose_name='机房联系电话')),
                ('email', models.EmailField(max_length=254, verbose_name='机房练习email')),
                ('letter', models.CharField(max_length=5, verbose_name='idc 字母简称')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='man',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Manufacturer'),
        ),
    ]
