# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-06 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='name',
            field=models.CharField(max_length=255, verbose_name='机柜名'),
        ),
    ]
